packages:
  - 'memory-test'
  - 'milvus-test'
  - 'output-parser-test'
  - 'prompt-template-test'
  - 'rag-test'
  - 'tool-test'
  - 'runnable-test'
  - 'hello-nest-langchain'
  - 'cron-job-tool'
allowBuilds:
  protobufjs: false
  unrs-resolver: true
minimumReleaseAgeExclude:
  - html-to-text@10.0.1
